class QA:
  def __init__(self, question, correctAnswer, otherAnswers):
    self.question = question
    self.corrAnsw = correctAnswer
    self.otherAnsw = otherAnswers
    
easy = [QA("____________ states that each point on a wave front may be considered a new wave source.","Huygens’s Principle ", ["Snell's Law ", "Young's Law","Hertz's Law"]),
          QA("A phase difference ∏ between two light waves is equivalent to the path difference ", "λ/2 ", ["2λ  ", "λ", " λ/4"]),
          QA("Interference of light is shows that:  ", "Light is a wave phenomenon ", ["The speed of light is very large", "Light is a transverse wave", " Light is electromagnetic in character"]),
          QA("When a light wave suffers reflection at the interface between air and glass medium, the change of phase of the reflected wave in air is equal to ______.  ", "π", ["0 ", "2π   ", "π/2"]),
          QA("The diameter of dark rings in Newton’s rings is", "Directly proportional to the square root of natural numbers", ["Inversely proportional to the square root of natural numbers ", "Directly proportional to the square root of even numbers ", "Directly proportional to the square root of odd numbers "]),          
          QA("In Fraunhofer diffraction, the incident wave front should be …..  ", " Plane ", ["Elliptical ","Spherical  ", "Cylindrical "]), 
          QA("A grating has 6000 lines per cm. How many orders of light of wavelength 4500 Å can be seen? ", "3", ["2", "1", "4"]),
          QA("The condition for minima in Fraunhofer diffraction for single slit is esinθ = mλ, what is ‘θ’?", "Angle of diffraction at which rays are diffracted at slit", ["Angle of incidence of incident rays at the slit", "Angle at which diffracted rays strikes the screen ", "Angle between slit and screen"]),
          QA("Resolving power of grating is given by", " λ/dλ", ["dλ/λ", "λ/2 ", " none of these "]),
          QA("On a rainy day, small oil films on water show brilliant colors'. This is due to ", "Interference", ["Dispersion ", "Diffraction", "Polarization"]),
          QA("Interference in thin film is mainly because of ", "Division of amplitude", ["Division of wave fronts", "Addition of amplitude", "Addition of wave fronts"]),
          QA("A monochromatic (single frequency, single wavelength) light ray in air (n = 1) enters a glass prism (n = 1.5). In the glass prism ", "The frequency is the same, but the wavelength is smaller than in air. ", ["Both the frequency and the wavelength are the same as in air ", "The frequency is the same, but the wavelength is greater than in air.", "The wavelength is the same, but the frequency is greater than In air "]),
          QA("A color with a wavelength longer than that of yellow is: ", "Red ", ["Blue", "Violet", "Green"]),
          QA("The diffraction observed by diffraction grating can also be Termed as _____ .  ", "Multiple Slit Diffraction  ", ["Single slit diffraction  ", "Fresnel’s Diffraction", "Double slit Diffraction"]),
          QA("In Newton’s rings experiment, if monochromatic source of light is replaced by another monochromatic source of higher wavelength. What will be the effect on radius (or diameter)?  ", "Radius (or diameter) will increase", ["Radius (or diameter) will decrease ", "Radius (or diameter) will remain constant but there will be more brightness ", "There will be no effect"]),
          QA("Density of states function implies ", " Number of available energy levels of electrons in unit volume per unit energy interval ", ["Number of available energy levels of electrons in unit volume per unit temperature ", "Number of available energy levels of electrons in unit volume ", "Number of available electrons of per unit volume of the solid "]),
          QA("Holes can exist in ____________ ", "Semiconductors", [" Conductors ", "Insulators ", "Superconductors"]),
          QA("The Fermi level is ", "The highest occupied energy level at 0 K ", ["An average value of all available energy levels ", " The highest occupied energy level at 0 C ", "An energy level at the top of the valence band "]),
          QA("Thermistors can sense ", "Changes in temperature", ["Changes in number of holes ", "Changes in pressure",  "Changes in number of electrons"]),
          QA("Pure silicon at 0 K is ____________ ", "Insulator", ["Metal", "Intrinsic Semiconductor", "Extrinsic Semiconductor"]),
          QA("The electrons in conduction band are free to", "Transport charge", ["Transport signals", "Transport impulses", "Transport vibrations"]),
          QA("Which one has the greatest energy gap ?", "Non metals", ["Semi conductor", "Conductor", "Metals"]),
          QA("Many of the semi conductors are crystals of the type", "Face centred cubic", ["Simple cubic", "Body centred cubic", "All of the Mentioned"]),
          QA("With increase in temperature the electrical conductivity of intrinsic semi conductor", "Increases", ["Decreases", "First increases then decreases", "Remains same"]),
          QA("On the basis of band theory of solids the semiconductors have", "A completely filled valence band a partially filled conduction band and a narrow forbidden band", ["A party filled valence band and totally empty conduction band", "A completely filled valence band a totally empty conduction band and a very wide forbidden band", "A partly filled valence band a totally empty conduction band and a wide forbidden band"]),
          QA("In a semiconductors the charge carriers are", "Electron and holes both", ["Electrons only", "Holes only", "All of the mentioned"]),
          QA("The net charge on n-type material is", "Neutral", ["Positive", "Negative", "Both positive and negative"]),
          QA("Very weak magnetic fields are detected by", "Squids", ["Magnetic resonance imaging (MRI)", "Magnetometer", "Oscilloscope"]),
          QA("Energy needed to magnetize and demagnetize is represented by", "Hysteresis loop area", ["Hysteresis curve", "Hysteresis loop", "Straight line"]),
          QA("The relation between horse power and watt is", "1 hp = 746 watts", ["1 hp = 546 watts", "1 hp = 900 watts", "1 hp = 646 watts"]),
          QA("Proton electron neutron and a particles have same momentum. Which of them have highest K.E?", "Electron", ["Proton", "Neutron", "a-particle"]),
          QA("Slope of work time graph is equal to", "Power", ["Displacement", "Acceleration", "Energy"]),
          QA("One mega watt hour is equal to", "36 x 10^8 J", ["36 x 10^7 J", "36 x 10^12 J", "36 x 10^9 J"])]


moderate=[ QA("____________ theory gives the origin of energy bands. ", "Kronig-Penney", ["Wien’s ", "Electron", "Fermi-Dirac"]),
          QA("Which of the following statement correctly describes a metal within a band theory? ", "A material possessing zero energy gap ", ["A material possessing infinite energy gap ", "A material possessing moderate energy gap ", "A material possessing large energy gap"]),
          QA("In a semiconductor, the energy gap between the valence band and conduction band is about ____________. ", "1 eV ", ["10 eV ", "5 eV ", "0 eV "]),
          QA("In Newton's ring experiment, the diameter of the 15 th ring was found to be 0.590 and that of the 5 th ring was 0.336 cm. If the radius of Plano convex lens is 100 cm, compute the wavelength of light used.", "5880 Å ", ["5890 Å", "5850 Å ", "5885 Å"]),
          QA("To find prominent diffraction , the size of diffraction object should be  ", "Comparable to order of wavelength of light ", ["Greater than wavelength of light used", "None of these. ", "Less than wavelength of light used  "]),
          QA("In Newton’s rings experiment, if we reduce the radius of curvature of Plano convex lens to zero, what will be effect on Newton’s rings?", "They will disappear ", ["They will be more dense ", "They will become darker ", "They will become brighter "]),
          QA("Fresnel’s type diffraction is observed when _________ ", "Both source and screen are at finite distance", ["Neither source nor screen are at finite distance", "Only source is placed at finite distance", "Only screen is placed at finite distance"]),
          QA("Fraunhofer diffraction at a Plane Grating What is the meaning of grating element for a diffraction grating?", "It is the distance between two slits", ["It is the width of a single slit", " It is the width of the opaque space", "It is the width of diffraction grating"]),
          QA("The grating used to observe, diffraction of visible light can have approximately", "15000 lines per cm", ["3000 lines per cm ", "300 lines per cm ", "30 lines per cm"]),
          QA("Free electron theory is based on which of the following assumption?", "Electrons behaves are freely moving through entire the solid", ["Electrons can move freely only along the surfaces of the solid", "Electrons are freely moving only at the centre of the solid", "Electrons can move freely only at the top surface of the solid"]),
          QA("At 0 K, all the valence electrons in an intrinsic semiconductor are ____________.", "In the valence band", ["Free electrons ", "In the forbidden gap", "In the conduction band"]),
          QA("Calculate the Hall Effect coefficient when number of electrons in a semiconductor is 10^20", "0.0625", ["625", "6.25", "0.625"]),
          QA("The efficiency of a solar cell is usually in the range ____________ ", "10-20%", ["50-70%", "20-50%", "2-5%"]),
          QA("Hall effect is true for ____________", "Both Metals and Semiconductors ", ["P-type Semiconductors ONLY ", "Metals ONLY ", "Semiconductors ONLY"]),
          QA("What is true about the diffusion current?", "Diffusion current is due to non-uniform distribution of holes and electrons ", ["Diffusion current is due to presence of holes ONLY ", "Diffusion current is due to formation of depletion layer ", "Diffusion current is due to the movement of electrons under the influence of electric field"]),
          QA("When PN junction is in forward bias, by increasing the battery voltage", "Current through P-N junction increases", ["Circuit resistance increases", "None of the Mentioned", "Current through P-N junction decreases "]),
          QA("In holographic data storage, the information is stored in ______________", "Crystals", ["Pendrives", "Diode", "Cells"]),
          QA("The technique by which image is obtained from a hologram is called as ____________", "Reconstruction", ["Formation", "Construction", "Projection"]),
          QA("Which of the following is used for the formation of holograms?", "Lasers", ["Visible", "X-rays", "UV-rays"]),
          QA("The information in the hologram exists in ________", "Coded form", ["Colored Image form", "Black and white image form", "3-D image form"]),
          QA("Holography is based on the principle of _________", "Interference", ["Difraction", "Polarization", "Interferometer"]),
          QA("The principle of generation of the wavefront from an object from a hologram can be used for _________", "Pattern recognition", ["Data Storage", "Transient Microscopy", "Interferometry"]),
          QA("The holograms found on credit-cards are an example of ________", "Rainbow Holograms", ["Reflection Hologram", "Hybrid Hologram", "Volume Holograms"]),
          QA("Which of the following is the characteristic of a black body?", "A perfect radiator and a perfect absorber", ["A perfect conductor", "A perfect radiator but an imperfect absorber", "A perfect absorber but an imperfect radiator"]),
          QA("Rayleigh-Jean’s law holds good for which of the following?", "Longer wavelength", ["Shorter Wavelength", " High energy", "High temperature"]),
          QA("Which of the following does not affect the photon?", "Magnetic or electric field", ["Light waves", "Gravity", "Current"]),
          QA(" Wien’s displacement law holds good only for ", "Shorter Wavelength", ["Longer Wavelength", "High energy", "High temperature"]),
          QA("What is Compton shift?", "Shift in wavelength", ["Shift in charge", "Shift in frequency", "Shift in radiation"]),
          QA("Compton shift depends on which of the following?", "Angle of scattering", ["Amplitude of frequency", "Incident radiation", "Nature of scattering substance"]),
          QA("Which of the following substances posses the highest elasticity?", "Steel", ["Glass", "Copper", "Rubber"]),
          QA("What is the SI unit of modulus of elasticity of substance?", "Nm-2", ["Jm-2", "Nm-1", "Being a number it has no unit."]),
          QA("What are the dimensions of stress?", "ML-1T-2", ["MLT-2", "ML-2T-1", "ML-3T-1"]),
          QA("The figure shown the stress-strain graph of a certain substance. Over which region of the graph is Hooks law obeyed?", "ED", ["AB", "BC", "CD"]),
          QA("Which of the following is not conservative force", "Friction", ["Gravitation", "Electric", "Magnetic"])]


tough=[QA("In plane transmission grating, the angle of diffraction for second order maxima for wavelength 5 x 10 -5 cm is 30 degrees . Calculate the number of lines in one centimeter of the grating surface.", "5000 lines/cm", ["500 lines/cm", "10000 lines/cm", "1000 lines/cm"]),
          QA("Find the maximum value of resolving power of a grating 3 cm wide having 5000 lines per cm, if the wavelength of light used is 5890A", "45000", ["5000 ", "4500", "40000"]),
          QA("In Fraunhofer diffraction pattern for single slit, a central maximum is obtained when angle of diffraction q is equal to zero. What it actually indicates?", "All the diffracted rays are perpendicular and focused by slit at a single point on screen", ["The rays are diffracted by the slit in all the directions", "None of the Mentioned", "All the diffracted rays are parallel and focused by slit at a single point on screen"]),
          QA("Why in Newton’s rings setup, the beam splitter (mirror) is kept at 450 ? ", "It allows light rays to incident at 900 over the top surface of Plano- convex lens", ["It allows light rays to incident uniformly over the top surface of Plano- convex lens", "It allows light rays to incident parallel over the top surface of Plano- convex lens ", "It allows light rays to incident at 450 over the top surface of Plano- convex lens "]),
          QA("The probability of occupancy of electrons above Fermi level at T=0K is ___________ ", "0%", ["50%", "100%", " Infinite"]),
          QA("An electron in crystal lattice experiences ___________ potential", "Periodic", ["Zero", "Uniform", "Random"]),
          QA("The depletion region of a P-N junction is one that is depleted of _________", " Mobile charges ", [" Immobile charges ", "Ions", "Atoms"]),
          QA("At very high temperature, a P-type semiconductor turns into ___________ ", "Intrinsic semiconductor", ["Extrinsic semiconductor ", "P-N junction diode", " N-type semiconductor"]),
          QA("Which one of the following physical quantities does not have the dimensions of force per unit area?", "Strain", ["Stress", "Youngs modulus", "Pressure"]),
          QA("A rubber cord of cross-sectional area 2cm2 has a length of 1m. When a tensile force of 10N is applied the length of the cord increases by 1cm. What is the youngs modulus of rubber?", "5x10^6 Nm-2", ["2x10^8 Nm-2", "0.5x10^-6 Nm-2", "0.2x10^-6Nm-2"]),
          QA("A wire suspended vertically from one end is stretched by attaching a weight of 20N to the lower end. The weight stretches the wire by 1mm. How much energy is gained by the wire?", "0.01J", ["0.02J", "0.04J", "1.0J"]),
          QA("Coercive force is the force which opposes", "Demagnetization", ["Breakage", "Extension", "Surface cracking"]),
          QA("Materials in which valence electrons are tightly bound to their atoms at low temperature are called", "Insulators", ["Semi conductor", "Super conductors", "Conductor"]),
          QA("The bulk properties of materials such as their mode of fracture can be related to their", "Microstructure", ["Dislocation", "Cleavage", "Polymerization"]),
          QA("A uniform steel wire of length 4m and area of cross-section 3x10-6m2 is extended by 1mm by the application of a force. If the youngs modulus of steel is 2x10^11 Nm-2 the energy stored in the wire is", "0.75J", ["0.025J", "0.50J", "0.100J"]),
          QA("The ration stress to strain in youngs modulus of the material then tension is", "Directly proportional to extension.", ["Directly proportional to strain.", "Inversely proportional to extension.", "Directly proportional to square of amplitude."]),
          QA("Materials that undergo plastic deformation before breaking are called", "Ductile", ["Brittle", "Amorphous", "Polymer"]),
          QA("Work done will be maximum if the angle between the force F and displacement d is", "0", ["90", "45", "180"]),
          QA("A field in which the work done in a moving a body along closed path is zero is called", "Conservative field", ["Electric field", "Gravitational field", "Electromagnetic field"]),
          QA("When a force is parallel to the direction of motion of the body, then work done on the body is", "Maximum", ["Minimum", "Infinity", "Zero"]),
          QA("Which of the following types of force can do no work on the particle on which it acts?", "Centripetal force", ["Gravitational force", "Fictional force", "Elastic force"]),
          QA("If a body a mass of 2 kg is raised vertically through 2m, then the work done will be", "39.2 J", ["38.2 J", "392.1 J", "3.92 J"]),
          QA("An elevator weighing 3.5 x 10-6 N is raised to a height of 1000 m in the absence of friction, the work done is", "3.5 x 10^9 J", ["3.5 x 10^6 J", "3.5 x 10^4 J", "3.5 x 10^3 J"]),
          QA("The average power and instantaneous power become equal if work is done at", "At uniform rate", ["At variable rate", "At any rate", "At high rate"]),
          QA("Work has the dimension as that of same as that of", "Torque", ["Linear momentum", "Angular momentum", "Power"]),
          QA("The consumption of energy by a 60 watt bulb in 2 sec is", "120 J", ["90 J", "60 J", "0.02 J"]),
          QA("The escape velocity form the earth surface in km S-1 is", "1.1 km S-1", ["4.2 km S-1", "9.5 km S-1", "7.5 km S-1"]),
          QA("If moon radius is 1600 km and g on its surface is 1.6 ms-2 then the escape velocity on the moon is", "50.6 ms-1", ["1600 ms-1", "71.6 ms-1", "2263ms-1"]),
          QA("When two protons are brought together", "P.E. between them increases", ["Kinetic energy increases", "P.E. between them decreases", "P.E. between tem does not change"]),
          QA("When arrow is released form its bow, its energy is transformed from", "Elastic P.E to K.E", ["Heat energy to K.E", "Elemical energy to elastic P.E", "K.E to elastic P.E."]),
          QA("A man lifts vertically a weight of 40kg through 1m in 10s; while a chile lifts vertically a weight of 10kg through a distance of 1m in 1s. What will be correct inference?", "Child does more work than man", ["Both do the same amount of work", "It is a foolish question", "Man does more work than child"]),
          QA("Geothermal energy is a ____________ source of energy.", "Renewable", ["Non-renewable", "Stable", "None of the Mentioned"]),
          QA("The source of tidal energy is", "Moon", ["Sun", "Earth", "Sun and Earth"])]

